from django.conf.urls import patterns, include, url
from web import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^cadastrar/$', views.cadastrar, name='cadastrar'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^configuracao_inicial/$', views.configuracao_inicial, name='configuracao_inicial'),
    url(r'^home/$', views.home, name='home'),
    url(r'^clientes/$', views.clientes, name='clientes'),
    url(r'^clientes/cadastrar/$', views.cadastrar_clientes, name='cadastrar_clientes'),
    url(r'^clientes/(?P<cliente_id>\d+)/$', views.visualizar_clientes, name='visualizar_clientes'),
    url(r'^clientes/(?P<cliente_id>\d+)/alterar/$', views.alterar_clientes, name='alterar_clientes'),
    url(r'^clientes/(?P<cliente_id>\d+)/excluir/$', views.excluir_clientes, name='excluir_clientes'),
    url(r'^representadas/$', views.representadas, name='representadas'),
    url(r'^representadas/cadastrar/$', views.cadastrar_representadas, name='cadastrar_representadas'),
    url(r'^representadas/(?P<representada_id>\d+)/$', views.visualizar_representadas, name='visualizar_representadas'),
    url(r'^representadas/(?P<representada_id>\d+)/alterar/$', views.alterar_representadas, name='alterar_representadas'),
    url(r'^representadas/(?P<representada_id>\d+)/excluir/$', views.excluir_representadas, name='excluir_representadas'),
    url(r'^transportadoras/$', views.transportadoras, name='transportadoras'),
    url(r'^transportadoras/cadastrar/$', views.cadastrar_transportadoras, name='cadastrar_transportadoras'),
    url(r'^transportadoras/(?P<transportadora_id>\d+)/$', views.visualizar_transportadoras, name='visualizar_transportadoras'),
    url(r'^transportadoras/(?P<transportadora_id>\d+)/alterar/$', views.alterar_transportadoras, name='alterar_transportadoras'),
    url(r'^transportadoras/(?P<transportadora_id>\d+)/excluir/$', views.excluir_transportadoras, name='excluir_transportadoras'),
    url(r'^produtos/$', views.produtos, name='produtos'),
    url(r'^produtos/cadastrar/$', views.cadastrar_produtos, name='cadastrar_produtos'),
    url(r'^produtos/(?P<produto_id>\d+)/$', views.visualizar_produtos, name='visualizar_produtos'),
    url(r'^produtos/(?P<produto_id>\d+)/alterar/$', views.alterar_produtos, name='alterar_produtos'),
    url(r'^produtos/(?P<produto_id>\d+)/excluir/$', views.excluir_produtos, name='excluir_produtos'),
    url(r'^pedidos/$', views.pedidos, name='pedidos'),
    url(r'^pedidos/cadastrar/$', views.cadastrar_pedidos, name='cadastrar_pedidos'),
    url(r'^contatos_clientes/(?P<contato_id>\d+)/$', views.lista_contatos_cliente, name='lista_contatos_cliente'),
    url(r'^produtos_representadas/(?P<representada_id>\d+)/$', views.lista_produtos_representada, name='lista_produtos_representada'),
    url(r'^produtos_representadas_editar/(?P<representada_id>\d+)/$', views.lista_produtos_representada_editar, name='lista_produtos_representada_editar'),
    url(r'^tabela_preco_produto/(?P<produto_id>\d+)/$', views.lista_tabela_preco_produto, name='lista_tabela_preco_produto'),
    url(r'^pedidos/(?P<pedido_id>\d+)/$', views.visualizar_pedidos, name='visualizar_pedidos'),
    url(r'^pedidos/(?P<pedido_id>\d+)/alterar/$', views.alterar_pedidos, name='alterar_pedidos'),
    url(r'^pedidos/(?P<pedido_id>\d+)/excluir/$', views.excluir_pedidos, name='excluir_pedidos'),
    url(r'^agenda/$', views.agenda, name='agenda'),
    url(r'^agenda/cadastrar/$', views.cadastrar_agenda, name='cadastrar_agenda'),
    url(r'^usuarios/$', views.usuarios, name='usuarios'),
    url(r'^usuarios/cadastrar/$', views.cadastrar_usuarios, name='cadastrar_usuarios'),
    url(r'^usuarios/(?P<usuario_id>\d+)/$', views.visualizar_usuarios, name='visualizar_usuarios'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)